#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

FROM ubuntu:18.04

ARG sdk_version=0.13.20

WORKDIR /home/sdk

COPY target/bond-issuance.dar /home/sdk/
COPY scripts/install-daml.sh /home/sdk/

RUN /bin/bash -c "apt-get update --no-show-upgraded &&  apt-get install wget openjdk-8-jdk postgresql postgresql-contrib -y"
RUN /home/sdk/install-daml.sh ${sdk_version}
RUN service postgresql start && \
    apt-get install sudo && \
    (echo postgres | sudo -u postgres createdb --username=postgres --password sandbox) && \
    sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password 'postgres';"
RUN echo "local   all         postgres                          md5" >> /etc/postgresql/10/main/pg_hba.conf

EXPOSE 7600

CMD service postgresql start && \
    ~/.daml/bin/daml sandbox -- --sql-backend-jdbcurl "jdbc:postgresql://localhost:5432/sandbox?user=postgres&password=postgres" \
    --port 7600 bond-issuance.dar
