#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.38

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY target/bond-issuance.dar /home/daml/

# Need the root user to set appropriate ownership of the DAR file.
USER root
RUN chown daml bond-issuance.dar
USER daml

EXPOSE 6865

CMD ~/.daml/bin/daml sandbox -- --wall-clock-time --port 6865 bond-issuance.dar
