#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

ARG sdk_vsn=0.13.27

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/sdk

COPY target/bond-issuance.dar /home/sdk/

EXPOSE 7600

CMD ~/.daml/bin/daml sandbox -- --wall-clock-time --port 7600 bond-issuance.dar
