#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: digitalasset/daml-sdk:0.12.15-circleci-master


jobs:
  mvn_test:
    executor: daml-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2
      - run:
          command: mvn verify
      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
      - run:
          name: Run Blackduck Detect
          command: |
              bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.docker.image=alpine:latest --detect.blackduck.signature.scanner.disabled=true --blackduck.blackduck.offline.mode=true --detect.docker.passthrough.imageinspector.service.start=true --blackduck.api.token=${HUBDETECT_TOKEN} --logging.level.com.blackducksoftware.integration=INFO --blackduck.url=https://digitalasset.blackducksoftware.com

  daml_test:
    executor: daml-executor
    steps:
      - checkout
      - run:
          command: |
            mkdir -p target/daml-test-reports
            da compile
            da run -- damlc test --junit target/daml-test-reports/daml-test.xml src/main/daml/DA/RefApps/Bond/Test/FullScenario.daml
      - store_test_results:
          path: target/daml-test-reports
      - store_artifacts:
          path: target/daml-test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - daml_test
      - mvn_test:
          context: blackduck
