#!/usr/bin/env bash
#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

export JAVA_TOOL_OPTIONS=-Xmx128m
scripts/waitForSandbox.sh localhost 6865
scripts/startTriggers.sh localhost 6865 target/bond-issuance-triggers.dar
